### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by zanger1234** [Zetrith/Prepatcher#12]
I'm getting this bug where the game is just stuck on the loading screen with prepatcher installed. I press launch, and the game opens the debug log and gets stuck. I waited 15 minutes, and it doesn't enter the main menu.

Here is the player.log with -verbose command enabled.

https://pastebin.com/TCuRE4Cc

many thanks.

**Comment by zanger1234** [comment]
Update: 
I narrowed the issue down to RimForge. As soon as I removed the mod from the modlist, the game ran fine with prepatcher enabled.

**Comment by Zetrith** [comment]
Yeah, right now when Prepatcher encounters an error during very early loading it just goes to the error console. I should probably change that

**Comment by Zetrith** [comment]
I pushed a fix to Steam 66e01b
