### ISSUE TITLE
Stuck without menu and only a log screen after disabling prestarter

### ISSUE THREAD

**Issue by fluff-y** [Zetrith/Prepatcher#13]
After disabling prestarter in the settings and restarting Rimworld, the game gets stuck when with main game background loaded but no main menu.
The only active mod is Prepatcher

**Comment by Zetrith** [comment]
Can you post a screenshot of the screen the game gets stuck on?

**Comment by fluff-y** [comment]
Rimpy
![0_RimPy](https://user-images.githubusercontent.com/56023678/224565702-aeb6ca1f-37df-4a62-a6ef-2ce261eb64b8.png)

Debug Window open
![1_Debug_Log](https://user-images.githubusercontent.com/56023678/224565706-51804b40-f0fb-40a1-b8b0-a9a2d53b430a.png)
There are some warnings & errors, but none related to any active Mod.

Debug Window closed
![1_Log_Closed](https://user-images.githubusercontent.com/56023678/224565708-8887b1ea-8991-457c-9447-9ab18362de96.png)

**Comment by Zetrith** [comment]
I pushed a fix to Steam 66e01b7
