### ISSUE TITLE
Game unable to start because of Prepatcher Error

### ISSUE THREAD

**Issue by Limfjorden** [Zetrith/Prepatcher#16]
The game is unable to load any mods after prepatcher and refuses to start. I am using with a bunch of mods, but that should be something prepatcher is made for right?

Log: https://pastebin.com/5u8CQUXh

**Comment by Zetrith** [comment]
What operating system / version of the game are you on? Can you start the game with the `-verbose` command line argument and upload the log file?

**Comment by Zetrith** [comment]
Thanks, I pushed a fix to Steam. Turns out RimWorld's assemblies differ slightly between Windows and Linux.

**Comment by Limfjorden** [comment]
> Thanks, I pushed a fix to Steam. Turns out RimWorld's assemblies differ slightly between Windows and Linux.

I am on a mac, so maybe the Linux fix will work for me too (both UNIX).
