### ISSUE TITLE
Blank screen and never loads

### ISSUE THREAD

**Issue by Agent-Bosnia** [Zetrith/Prepatcher#17]
Log thing: https://pastebin.com/3KFmyum2

I know for a fact that this mod causes it because without it the game loads perfectly fine

**Comment by Zetrith** [comment]
From the log I assume the screen isn't blank but is showing the dev console. If that's right I'll fix it soon.
As for the cause it appears that your RimForge is broken.

**Comment by lilithwhite** [comment]
Seems this mod has issues with RimForge. Game loads fine without this mod and with RimForge and also loads fine without RimForge but with this mod. If both this and RimForge are present it gets stuck in the debug menu.

**Comment by Zetrith** [comment]
Shouldn't be an issue anymore
