### ISSUE TITLE
Prepatcher leads to the game crashing when loading the main menu

### ISSUE THREAD

**Issue by Rosalina-Chan** [Zetrith/Prepatcher#18]
I have only got Prepatcher, Core, Royalty, Ideology, and Biotech enabled. 
I do have several mods downloaded through Steam (I have not added any mods in a few days), however they are disabled and I fully reinstalled the game within the last few hours (Rimworld was crashing with similar/the same logs before I reinstalled everything). 
In addition launching the game from Steam itself or RimPy causes it to have the same issue.
Prepatcher was working completely fine for me until today, I subscribed to the mod around the 19th of April if that means anything.
Also I have no errors from my modlist if I load it without Prepatcher.

Player.log file (Only Prepatcher + Vanilla enabled), -verbose enabled: https://pastebin.com/vy8TCta4

If you need me to provide anything else, or if I've been an idiot, then please do let me know.
P.s. I love the mod concept and really appreciate the hard work you've put into it.

**Comment by Zetrith** [comment]
Thanks for the report. There don't seem to be any exceptions in the log. Does the game just crash to desktop? Is there some other error message? When does it crash (do you see the Prestarter mod manager)?

**Comment by Zetrith** [comment]
I'll close it for now but that's a strange problem. If you get any more information please post it here.
