### ISSUE TITLE
Black screen on prepatcher launch

### ISSUE THREAD

**Issue by elkillo** [Zetrith/Prepatcher#19]
I'm not the greatest as deciphering Logs but it seems to be vanilla expanded framework is causing an issue. Attached is the log file if you would like to take a look. If you need me to do anything to troubleshoot let me know. 
[Player.log](https://github.com/Zetrith/Prepatcher/files/12202604/Player.log)

**Comment by Zetrith** [comment]
It should be fixed now

**Comment by elkillo** [comment]
do i need to redownload to resolve?

**Comment by Zetrith** [comment]
I uploaded the fix in https://github.com/Zetrith/Prepatcher/releases if you aren't using Steam
