### ISSUE TITLE
Root level exception in Update(): System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by KyleMHB** [Zetrith/Prepatcher#5]
Im using rimworld 1.2 with Royalty and 355 mods.

[Modlist](https://hastebin.com/ihojufohej)

I recently went through the Dub Wise Mods shitlist to remove performance destroying mods, and they have a few recommendations and alternatives to existing mods that have issues.
I have tested and when using prepatcher and the mod fixes from Karwise on the [Dubs Mod Discord](https://discord.gg/PEb9uC9)
I am getting a black screen on load (of new games or on existing saves), similar to the other issue that was closed - game runs I can see it on the minimap just nothing on the main window, image below.

My mod list fixes using prepatcher: (ignore the ones with red lines)
![image](https://user-images.githubusercontent.com/23214110/91145481-cfeb6100-e6b5-11ea-81e4-c4ee381478ef.png)

Root level exception in Update(): System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) Verse.SkyManager.Verse.SkyManager.SkyManagerUpdate_Patch1(Verse.SkyManager)
  at (wrapper dynamic-method) Verse.Map.Verse.Map.MapUpdate_Patch1(Verse.Map)
  at (wrapper dynamic-method) Verse.Game.Verse.Game.UpdatePlay_Patch3(Verse.Game)
  at (wrapper dynamic-method) Verse.Root_Play.Verse.Root_Play.Update_Patch1(Verse.Root_Play)
Verse.Log:Error(String, Boolean)
Verse.Root_Play:Verse.Root_Play.Update_Patch1(Root_Play)

![](https://cdn.discordapp.com/attachments/660280287497814078/747620384790282240/unknown.png)

![](https://cdn.discordapp.com/attachments/660280287497814078/747591530797072484/unknown.png)

**Comment by Zetrith** [comment]
Could you open your log file and see what the very first exceptions are? The later ones are usually useless.
Also, could you try to isolate a minimal set of mods for reproduction?

**Comment by KyleMHB** [comment]
I am trying to, I have taken out the fixes and left prepatcher in to see if that makes a difference.

Does prepatcher output a log of the patches so I can see what is being patched to isolate those mods?

**Comment by Zetrith** [comment]
It's probably not the patches that other mods add themselves. Could you send your whole log file here?

**Comment by KyleMHB** [comment]
[Player.log](https://github.com/Zetrith/Prepatcher/files/5123975/Player.log)

Here you go

**Comment by KyleMHB** [comment]
Karwise advised me it is likely not an issue with prepatcher and requested I close this issue.

Thank you for the help - I'll try come right.
